### ISSUE TITLE
is this repo maintained?

### ISSUE THREAD

**Issue by shirbr510** [prayerslayer/koa-prometheus#1]
first of all, nice piece of code there 😄 

now, as a 2 years old repository, the has 1 version, is this repository maintained?

any testing plans? road map? anything?

**Comment by prayerslayer** [comment]
Oh hey, sorry for the late response. I probably didn't see the email notification. As for your questions:

> Is this repository maintained

I wrote it a couple of years ago because I needed it for a project of a company I no longer work for. My current company uses neither koa nor Prometheus, and I don't need it in my free time either. That's why there was no progress so far, it was good enough back then.

So I guess the answer is **no** but I'm happy to transfer the repo or give someone else push access. It's not widely used anyways so that should be safe.

> any testing plans?

Not really, the existing unit tests were good enough for me. What would you suggest?

> road map?

I won't spend time on a roadmap to improve software for 1–3 users :)

![image](https://user-images.githubusercontent.com/878512/51822099-8705d780-22db-11e9-8ff9-274c25545b24.png)

**Comment by shirbr510** [comment]
I was wondering cause I was trying to provide some sort of tool similar to `django-prometheus` and many other awesome prometheus clients.

in the meanwhile, I ended up implementing just a lean wrapper around prom-client and I'll probably create a proper koa-prometheus project sometime later in the future.

if you would like to move ownership, I think I can take it under my wing but just as you said: 

> I won't spend time on a roadmap to improve software for 1–3 users :)

so hopefully we'll be able to make this into something slightly bigger 😉 

I'm closing this issue but we can continue the discussion anyways 😄
